version: "3.9"  # optional since v1.27.0
services:
  web-app-service:
    build: ./client
    ports:
      - 80:3000

  rest-api-service:
    build: ./api
    ports:
      - 3001:3000
    depends_on: 
      - web-app-service

    volumes:
    - ./api:/usr/src/app

volumes:
  api: